name: Read Secrets File

on: workflow_dispatch

jobs:
  read-secrets-file:
    runs-on: ubuntu-latest
    steps:
      - name: Testing Secrets
        run: |
          echo "$DEVOPS"
          env:
            DEVOPS: ${{ secrets.SECRET_TOKEN }}
      - name: Read Environment Variables
        run: |
          echo "GITHUB_ACTIONS -  ${ secrets.GITHUB_ACTIONS}"
          echo "HOME: ${HOME}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_API_URL: ${GITHUB_API_URL}"
          echo "GITHUB_EVENT_PATH: ${GITHUB_EVENT_PATH}"
          echo "GITHUB_JOB: ${GITHUB_JOB}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_OS: ${GITHUB_OS}"
